import { NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";

export async function GET(request:Request){
  const secret=process.env.CRON_SECRET;const authorization=request.headers.get("authorization");
  if(!secret||authorization!==`Bearer ${secret}`)return NextResponse.json({error:"Não autorizado."},{status:401});
  const apiKey=process.env.BREVO_API_KEY;const senderEmail=process.env.BREVO_SENDER_EMAIL;const senderName=process.env.BREVO_SENDER_NAME||"Comitê de Engenharia";
  if(!apiKey||!senderEmail)return NextResponse.json({error:"Configure BREVO_API_KEY e BREVO_SENDER_EMAIL para ativar os lembretes."},{status:503});
  const admin=createAdminClient();const {data:semester}=await admin.from("semesters").select("id,name").eq("status","active").maybeSingle();if(!semester)return NextResponse.json({ok:true,sent:0,message:"Nenhum semestre ativo."});
  const {data:demands}=await admin.from("demands").select("id,title").eq("semester_id",semester.id).neq("status","closed");const demandIds=(demands??[]).map(row=>row.id);if(!demandIds.length)return NextResponse.json({ok:true,sent:0});
  const [{data:deliverables},{data:assignments},{data:members}]=await Promise.all([admin.from("deliverables").select("id,demand_id,title,due_at").in("demand_id",demandIds).not("due_at","is",null),admin.from("demand_groups").select("demand_id,group_id").in("demand_id",demandIds),admin.from("group_members").select("group_id,user_id").eq("semester_id",semester.id)]);
  const deliverableIds=(deliverables??[]).map(row=>row.id);let submittedRows:Array<{deliverable_id:string;group_id:string}>=[];if(deliverableIds.length){const {data}=await admin.from("submissions").select("deliverable_id,group_id").in("deliverable_id",deliverableIds);submittedRows=data??[];}
  const userIds=[...new Set((members??[]).map(row=>row.user_id))];const {data:profiles}=userIds.length?await admin.from("profiles").select("id,name,email").in("id",userIds):{data:[]};const profileMap=new Map((profiles??[]).map(profile=>[profile.id,profile]));const demandMap=new Map((demands??[]).map(demand=>[demand.id,demand]));const submitted=new Set(submittedRows.map(row=>`${row.deliverable_id}:${row.group_id}`));let sent=0,failed=0;
  for(const delivery of deliverables??[]){if(!delivery.due_at)continue;const days=calendarDayDifference(new Date(),new Date(delivery.due_at));const kind=days===3?"three_days":days===1?"one_day":days===0?"today":days<0?"overdue":null;if(!kind)continue;for(const assignment of (assignments??[]).filter(row=>row.demand_id===delivery.demand_id)){if(submitted.has(`${delivery.id}:${assignment.group_id}`))continue;for(const member of (members??[]).filter(row=>row.group_id===assignment.group_id)){const profile=profileMap.get(member.user_id);if(!profile?.email)continue;const eventKey=`deliverable:${delivery.id}:group:${assignment.group_id}`;const {data:existing}=await admin.from("notification_deliveries").select("id").eq("user_id",member.user_id).eq("event_key",eventKey).eq("reminder_kind",kind).maybeSingle();if(existing)continue;const label=kind==="overdue"?"está atrasada":kind==="today"?"vence hoje":`vence em ${days} dia${days===1?"":"s"}`;const response=await fetch("https://api.brevo.com/v3/smtp/email",{method:"POST",headers:{"Content-Type":"application/json","api-key":apiKey},body:JSON.stringify({sender:{name:senderName,email:senderEmail},to:[{email:profile.email,name:profile.name||undefined}],subject:`${delivery.title} ${label}`,htmlContent:`<h2>${escapeHtml(delivery.title)}</h2><p>Olá, ${escapeHtml(profile.name||"participante")}.</p><p>A entrega <strong>${escapeHtml(delivery.title)}</strong>, da demanda <strong>${escapeHtml(demandMap.get(delivery.demand_id)?.title||"")}</strong>, ${label}.</p><p>Prazo: ${new Date(delivery.due_at).toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo"})}</p><p>Acesse o ambiente do seu grupo para acompanhar a pendência.</p>`})});const payload=await response.json().catch(()=>({}));await admin.from("notification_deliveries").insert({user_id:member.user_id,event_key:eventKey,reminder_kind:kind,recipient_email:profile.email,status:response.ok?"sent":"failed",provider_message_id:payload.messageId||null,error_message:response.ok?null:JSON.stringify(payload).slice(0,500),sent_at:response.ok?new Date().toISOString():null});if(response.ok)sent++;else failed++;}}}
  return NextResponse.json({ok:true,sent,failed});
}
function calendarDayDifference(from:Date,to:Date){const parts=(date:Date)=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo",year:"numeric",month:"2-digit",day:"2-digit"}).format(date).split("-").map(Number);const[a,b,c]=parts(from);const[x,y,z]=parts(to);return Math.round((Date.UTC(x,y-1,z)-Date.UTC(a,b-1,c))/86400000);}
function escapeHtml(value:string){return value.replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]!));}
